version: 2.1

executors:
  cimg-base:
    docker:
      - image: cimg/base:stable

parameters:
  build-ios:
    type: boolean
    default: false
  build-android:
    type: boolean
    default: false

jobs:
  check-workflow-status:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python .circleci/check-workflow-status.py <<pipeline.git.revision>>
  ios-ci:
    executor: cimg-base
    steps:
      - checkout
      - run: echo "iOS"
  android-ci:
    executor: cimg-base
    steps:
      - checkout
      - run: echo "Android"
workflows:
  check-workflow-status-workflow:
    jobs:
      - check-workflow-status
  ios-workflow:
    when: << pipeline.parameters.build-ios >>
    jobs:
      - ios-ci
  android-workflow:
    when: << pipeline.parameters.build-android >>
    jobs:
      - android-ci